"""Render the app's result HTML to a standalone file you can open in a browser.

Why this exists: the deployed page is judgeable at a glance, but seeing it
locally otherwise means installing torch and downloading ~2.7 GB of fine-tuned
weights. This writes a single self-contained HTML file instead, so the layout,
provenance chips, panel and footer can be reviewed -- and screenshotted for the
newsletter -- before anything is deployed.

The retrieval here is real, but it is **BM25 only**: keyword search is the one
mode that needs no model weights. The hybrid mode that the demo actually opens
on is rendered from seeded sample scores and labelled as such, so the layout can
be judged without pretending those numbers mean anything. Ranking quality for
the model-backed modes was verified separately in ``notebooks/verify_parity.ipynb``.

Run from the repository root:

    python prototype/scripts/make_preview.py
    # writes prototype/preview.html
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # for `app`, `src`
sys.path.insert(0, str(Path(__file__).resolve().parent))  # for `stub_retriever`

import app  # noqa: E402
from stub_retriever import build_stub_pipeline  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "preview.html"

# A spread of corpus subjects, so the preview does not show three variations on
# the same question.
QUERIES = [
    "When is the best time to plant rice in northern Nigeria?",
    "My maize leaves are turning yellow, what should I do?",
    "How do I control fall armyworm without chemicals?",
]

SAMPLE_NOTICE = (
    "<div class='ky-note'><strong>Sample scores.</strong> The fine-tuned models "
    "are not loaded on this machine, so this mode is rendered from seeded "
    "placeholder scores. The layout, chips and panel are exactly what deploys; "
    "the numbers are not.</div>"
)


def section(title: str, query: str, body: str, notice: str = "") -> str:
    return (
        f"<h2 style='margin:34px 0 2px 0; font-size:19px;'>{title}</h2>"
        f"<p style='margin:0 0 12px 0; opacity:.75;'>&ldquo;{query}&rdquo;</p>"
        f"{notice}{body}"
    )


def main() -> int:
    # Real BM25 index and real corpus; the stub only supplies the model-backed
    # scores. build_pipeline() already bailed out at import (placeholder model
    # IDs), so nothing in this script touches torch.
    pipeline, _ = build_stub_pipeline()

    def render(query: str, mode: str) -> str:
        return app.render(query, mode, pipeline=pipeline)

    sections = [
        # Real retrieval, no models required.
        section("BM25 only &mdash; real retrieval", query,
                render(query, "bm25_only"))
        for query in QUERIES
    ]

    # The mode a visitor lands on, so its design gets the most scrutiny.
    sections.append(
        section("Hybrid &mdash; the default mode", QUERIES[0],
                render(QUERIES[0], "hybrid"),
                SAMPLE_NOTICE)
    )

    page = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agricultural Extension RAG &mdash; layout preview</title>
<style>
  body {{
    max-width: 880px; margin: 0 auto; padding: 32px 18px 60px 18px;
    background: #ffffff; color: #111827;
  }}
  h2 {{ border-top: 1px solid rgba(127,127,127,.3); padding-top: 18px; }}
  .ky-banner {{
    border: 1px solid rgba(217,119,6,.5); background: rgba(217,119,6,.1);
    border-radius: 8px; padding: 12px 14px; font-size: 13.5px; line-height: 1.6;
  }}
</style>
</head>
<body>
<div class="ky-banner">
  <strong>Static layout preview.</strong> Generated by
  <code>prototype/scripts/make_preview.py</code> so the page design can be
  reviewed without downloading the models. The deployed Space renders this same
  markup inside Gradio, with the fine-tuned models producing every rank and
  score.
</div>
{''.join(sections)}
<hr style="margin:40px 0 20px 0; border:none; border-top:1px solid rgba(127,127,127,.3);">
<h2 style="border:none; padding-top:0;">Footer, as deployed</h2>
{app.ATTRIBUTION}
<p><em>This demo is a competition prototype, not field advice. Always confirm
guidance with a local extension officer.</em></p>
</body>
</html>
"""

    OUT.write_text(page, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Open in a browser:  {OUT.as_uri()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
